modLoader = "javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/TheBlackSquidward/SquidwardAPI/issues"
license = "https://github.com/TheBlackSquidward/SquidwardAPI/blob/master/LICENSE"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/TheBlackSquidward/SquidwardAPI"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange="${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"